"""
Renders a screenshot of the Tetris game by replicating the exact TetrisEngine
logic from the Kotlin source. Produces a PNG that matches the Compose UI layout
(dark background, board with ghost piece, HUD, next preview, controls).

The game state is generated by actually simulating moves so the screenshot
reflects a real mid-game board.
"""
import random
from PIL import Image, ImageDraw, ImageFont

# ---- Exact constants from TetrisEngine.kt ----
COLS = 10
ROWS = 20

DEFS = [
    # I
    ["....", "XXXX", "....", "...."],
    ["..X.", "..X.", "..X.", "..X."],
    ["....", "....", "XXXX", "...."],
    [".X..", ".X..", ".X..", ".X.."],
    # O (same for all rotations)
    [".XX.", ".XX.", "....", "...."],
    [".XX.", ".XX.", "....", "...."],
    [".XX.", ".XX.", "....", "...."],
    [".XX.", ".XX.", "....", "...."],
    # T
    [".X..", "XXX.", "....", "...."],
    [".X..", ".XX.", ".X..", "...."],
    ["....", "XXX.", ".X..", "...."],
    [".X..", "X...", "XX..", "...."],
    # S
    [".XX.", "XX..", "....", "...."],
    [".X..", ".XX.", "..X.", "...."],
    ["....", ".XX.", "XX..", "...."],
    ["X...", "XX..", ".X..", "...."],
    # Z
    ["XX..", ".XX.", "....", "...."],
    ["..X.", ".XX.", ".X..", "...."],
    ["....", "XX..", ".XX.", "...."],
    [".X..", "XX..", "X...", "...."],
    # J
    ["X...", "XXX.", "....", "...."],
    [".XX.", ".X..", ".X..", "...."],
    ["....", "XXX.", "..X.", "...."],
    [".X..", ".X..", "XX..", "...."],
    # L
    ["..X.", "XXX.", "....", "...."],
    [".X..", ".X..", ".XX.", "...."],
    ["....", "XXX.", "X...", "...."],
    ["XX..", ".X..", ".X..", "...."],
]
SHAPES = [
    [[row[c] == "X" for c in range(4)] for row in DEFS[t * 4 + rot]]
    for t in range(7) for rot in range(4)
]
SHAPES = [SHAPES[t * 4:(t + 1) * 4] for t in range(7)]

# ARGB Ints from Kotlin converted to (R,G,B) tuples
def argb(c):
    return ((c >> 16) & 0xFF, (c >> 8) & 0xFF, c & 0xFF)

COLORS = [argb(c) for c in [
    0xFF00E5FF, 0xFFFFD600, 0xFFC04CFF, 0xFF00E676,
    0xFFFF1744, 0xFF2979FF, 0xFFFF9100,
]]

# ---- UI palette (from TetrisScreen.kt / colors.xml) ----
BG_DARK = (0x0F, 0x0F, 0x1B)
PANEL_BG = (0x1B, 0x1B, 0x2E)
BOARD_BG = (0x1B, 0x1B, 0x2E)
ACCENT = (0x00, 0xE5, 0xFF)
TEXT_LIGHT = (255, 255, 255)
BTN_BG = (0x2A, 0x2A, 0x40)
GRID = (0x22, 0x22, 0x22)  # 0x22FFFFFF ~ subtle


# ---- Engine replication ----
class Engine:
    def __init__(self):
        self.board = [[0] * COLS for _ in range(ROWS)]
        self.score = 0
        self.lines = 0
        self.level = 1
        self.game_over = False
        self.next_type = random.randint(0, 6)
        self.spawn()

    def spawn(self):
        self.cur_type = self.next_type
        self.next_type = random.randint(0, 6)
        self.cur_rot = 0
        self.cur_row = 0
        self.cur_col = (COLS - 4) // 2
        if self.collides(self.cur_row, self.cur_col, self.cur_rot):
            self.game_over = True

    def collides(self, row, col, rot):
        shape = SHAPES[self.cur_type][rot]
        for r in range(4):
            for c in range(4):
                if not shape[r][c]:
                    continue
                br, bc = row + r, col + c
                if bc < 0 or bc >= COLS or br >= ROWS:
                    return True
                if br >= 0 and self.board[br][bc] != 0:
                    return True
        return False

    def lock(self):
        shape = SHAPES[self.cur_type][self.cur_rot]
        for r in range(4):
            for c in range(4):
                if shape[r][c]:
                    br, bc = self.cur_row + r, self.cur_col + c
                    if 0 <= br < ROWS and 0 <= bc < COLS:
                        self.board[br][bc] = self.cur_type + 1
        self.clear_lines()
        if not self.game_over:
            self.spawn()

    def clear_lines(self):
        cleared = 0
        r = ROWS - 1
        while r >= 0:
            if all(self.board[r][c] != 0 for c in range(COLS)):
                cleared += 1
                for rr in range(r, 0, -1):
                    self.board[rr] = self.board[rr - 1][:]
                self.board[0] = [0] * COLS
            else:
                r -= 1
        if cleared:
            self.lines += cleared
            pts = [0, 40, 100, 300, 1200]
            self.score += pts[cleared] * self.level
            self.level = 1 + self.lines // 10

    def move(self, dc):
        if not self.collides(self.cur_row, self.cur_col + dc, self.cur_rot):
            self.cur_col += dc
            return True
        return False

    def rotate(self):
        new_rot = (self.cur_rot + 1) % 4
        for kick in [0, -1, 1, -2, 2]:
            if not self.collides(self.cur_row, self.cur_col + kick, new_rot):
                self.cur_col += kick
                self.cur_rot = new_rot
                return True
        return False

    def tick(self):
        if not self.collides(self.cur_row + 1, self.cur_col, self.cur_rot):
            self.cur_row += 1
            return True
        self.lock()
        return False


def ghost_row(engine):
    gr = engine.cur_row
    while not engine.collides(gr + 1, engine.cur_col, engine.cur_rot):
        gr += 1
    return gr


# ---- Simulate to a realistic mid-game state ----
def best_drop_col(engine):
    """Pick the column/rotation that minimizes stack height (greedy)."""
    best = (1e9, engine.cur_rot, engine.cur_col)
    for rot in range(4):
        for col in range(-2, COLS + 2):
            # find landing row
            row = 0
            if engine.collides(row, col, rot):
                continue
            while not engine.collides(row + 1, col, rot):
                row += 1
            # simulate landing, count completed lines + aggregate height
            shape = SHAPES[engine.cur_type][rot]
            test = [r[:] for r in engine.board]
            bad = False
            for r in range(4):
                for c in range(4):
                    if shape[r][c]:
                        br, bc = row + r, col + c
                        if 0 <= br < ROWS and 0 <= bc < COLS:
                            test[br][bc] = 1
                        else:
                            bad = True
            if bad:
                continue
            heights = [0] * COLS
            for c in range(COLS):
                for rr in range(ROWS):
                    if test[rr][c]:
                        heights[c] = ROWS - rr
                        break
            agg = sum(heights)
            holes = 0
            for c in range(COLS):
                blocked = False
                for rr in range(ROWS):
                    if test[rr][c]:
                        blocked = True
                    elif blocked:
                        holes += 1
            lines = sum(1 for rr in range(ROWS) if all(test[rr]))
            score = agg - lines * 10 + holes * 2
            if score < best[0]:
                best = (score, rot, col)
    return best[1], best[2]


def make_state(seed=8):
    random.seed(seed)
    e = Engine()
    moves = 0
    while not e.game_over and moves < 25:
        rot, col = best_drop_col(e)
        e.cur_rot = rot
        # move toward target col
        for _ in range(6):
            if e.cur_col < col and e.move(1):
                pass
            elif e.cur_col > col and e.move(-1):
                pass
            else:
                break
        # hard drop
        while not e.game_over and e.tick():
            pass
        moves += 1
    return e


# ---- Rendering ----
def hex_font(sz):
    for path in [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]:
        try:
            return ImageFont.truetype(path, sz)
        except Exception:
            continue
    return ImageFont.load_default()


def draw_cell(d, x, y, cell, color):
    d.rectangle([x + 1, y + 1, x + cell - 1, y + cell - 1], fill=color)
    # bevel highlight
    d.rectangle([x + 2, y + 2, x + cell - 4, y + 4], fill=(255, 255, 255, 64))
    d.rectangle([x + 2, y + cell - 4, x + cell - 2, y + cell - 2], fill=(0, 0, 0, 50))


def render(engine, out_path, cell=28):
    pad = 16
    field_w = cell * COLS
    field_h = cell * ROWS

    # Layout dimensions
    hud_h = 50
    next_h = 90
    ctrl_h = 130
    side_pad = 24
    img_w = field_w + side_pad * 2
    img_h = hud_h + pad + field_h + pad + next_h + pad + ctrl_h + pad

    img = Image.new("RGBA", (img_w, img_h), BG_DARK + (255,))
    d = ImageDraw.Draw(img)
    f_big = hex_font(20)
    f_med = hex_font(16)
    f_sm = hex_font(12)
    f_btn = hex_font(18)

    # HUD
    y = pad
    d.text((side_pad, y), f"Score", fill=(180, 180, 180), font=f_sm)
    d.text((side_pad, y + 16), f"{engine.score}", fill=TEXT_LIGHT, font=f_big)
    lvl_x = img_w // 2 - 30
    d.text((lvl_x, y), "Level", fill=(180, 180, 180), font=f_sm)
    d.text((lvl_x, y + 16), f"{engine.level}", fill=ACCENT, font=f_big)
    d.text((img_w - side_pad - 90, y), "Lines", fill=(180, 180, 180), font=f_sm)
    d.text((img_w - side_pad - 90, y + 16), f"{engine.lines}", fill=TEXT_LIGHT, font=f_big)
    y += hud_h + pad

    # Board
    ox = (img_w - field_w) // 2
    oy = y
    d.rectangle([ox, oy, ox + field_w, oy + field_h], fill=BOARD_BG)

    # Locked cells
    for r in range(ROWS):
        for c in range(COLS):
            v = engine.board[r][c]
            if v != 0:
                draw_cell(d, ox + c * cell, oy + r * cell, cell, COLORS[v - 1])

    # Ghost piece
    if not engine.game_over:
        gr = ghost_row(engine)
        shape = SHAPES[engine.cur_type][engine.cur_rot]
        color = COLORS[engine.cur_type]
        for r in range(4):
            for c in range(4):
                if shape[r][c]:
                    x = ox + (engine.cur_col + c) * cell
                    yy = oy + (gr + r) * cell
                    # translucent outline
                    overlay = Image.new("RGBA", (cell - 4, cell - 4), (0, 0, 0, 0))
                    od = ImageDraw.Draw(overlay)
                    od.rectangle([0, 0, cell - 5, cell - 5],
                                 outline=color + (90,), width=3)
                    img.paste(overlay, (int(x + 2), int(yy + 2)), overlay)

    # Current piece
    if not engine.game_over:
        shape = SHAPES[engine.cur_type][engine.cur_rot]
        color = COLORS[engine.cur_type]
        for r in range(4):
            for c in range(4):
                if shape[r][c]:
                    draw_cell(d, ox + (engine.cur_col + c) * cell,
                              oy + (engine.cur_row + r) * cell, cell, color)

    # Grid lines
    grid = (255, 255, 255, 34)
    for c in range(COLS + 1):
        x = ox + c * cell
        d.line([(x, oy), (x, oy + field_h)], fill=grid)
    for r in range(ROWS + 1):
        yy = oy + r * cell
        d.line([(ox, yy), (ox + field_w, yy)], fill=grid)
    d.rectangle([ox, oy, ox + field_w, oy + field_h],
                outline=(255, 255, 255, 100))

    y = oy + field_h + pad

    # Next preview + pause button row
    d.text((side_pad, y + 30), "Next", fill=TEXT_LIGHT, font=f_med)
    nb_x = side_pad + 60
    nb_y = y + 10
    nb_s = 72
    d.rounded_rectangle([nb_x, nb_y, nb_x + nb_s, nb_y + nb_s],
                        radius=8, fill=PANEL_BG)
    ncell = nb_s // 4
    nshape = SHAPES[engine.next_type][0]
    ncolor = COLORS[engine.next_type]
    minr, maxr, minc, maxc = 4, -1, 4, -1
    for r in range(4):
        for c in range(4):
            if nshape[r][c]:
                minr = min(minr, r); maxr = max(maxr, r)
                minc = min(minc, c); maxc = max(maxc, c)
    pw = (maxc - minc + 1); ph = (maxr - minr + 1)
    nox = nb_x + (nb_s - pw * ncell) // 2 - minc * ncell
    noy = nb_y + (nb_s - ph * ncell) // 2 - minr * ncell
    for r in range(4):
        for c in range(4):
            if nshape[r][c]:
                d.rectangle([nox + c * ncell + 1, noy + r * ncell + 1,
                             nox + c * ncell + ncell - 1, noy + r * ncell + ncell - 1],
                            fill=ncolor)

    # Pause button
    pb_w, pb_h = 120, 50
    pb_x = img_w - side_pad - pb_w
    pb_y = y + 20
    d.rounded_rectangle([pb_x, pb_y, pb_x + pb_w, pb_y + pb_h],
                        radius=8, fill=BTN_BG)
    d.text((pb_x + 18, pb_y + 14), "Pause", fill=TEXT_LIGHT, font=f_btn)

    y += next_h + pad

    # Control buttons row 1
    bw = (img_w - side_pad * 2 - 12) // 3
    bh = 52
    labels1 = ["<", "v", ">"]
    for i, lab in enumerate(labels1):
        bx = side_pad + i * (bw + 6)
        d.rounded_rectangle([bx, y, bx + bw, y + bh], radius=8, fill=BTN_BG)
        tw = d.textlength(lab, font=f_btn)
        d.text((bx + (bw - tw) // 2, y + 14), lab, fill=TEXT_LIGHT, font=f_btn)

    y += bh + 6
    # Control buttons row 2
    bw2 = (img_w - side_pad * 2 - 6) // 2
    labels2 = ["Rotate", "Drop"]
    for i, lab in enumerate(labels2):
        bx = side_pad + i * (bw2 + 6)
        d.rounded_rectangle([bx, y, bx + bw2, y + bh], radius=8, fill=BTN_BG)
        tw = d.textlength(lab, font=f_btn)
        d.text((bx + (bw2 - tw) // 2, y + 14), lab, fill=TEXT_LIGHT, font=f_btn)

    img.convert("RGB").save(out_path, "PNG")
    print(f"Saved {out_path} ({img_w}x{img_h})")


if __name__ == "__main__":
    e = make_state(seed=8)
    # Place a piece partway down for a nice "in play" look.
    for _ in range(7):
        if e.game_over:
            break
        if not e.collides(e.cur_row + 1, e.cur_col, e.cur_rot):
            e.cur_row += 1
        else:
            break
    render(e, "/workspace/project/tetris_screenshot.png", cell=28)
    # higher-res version
    render(e, "/workspace/project/tetris_screenshot_hd.png", cell=40)
